<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>birth_month_dropdown</name>
   <tag></tag>
   <elementGuidId>8034d1fb-81e9-4743-9a1d-7f423723ef21</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='months']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#months</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>d39477aa-2844-4025-ba54-bade78288acd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-qa</name>
      <type>Main</type>
      <value>months</value>
      <webElementGuid>84244249-e59c-4306-8dc5-b8d8f53f4e91</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>months</value>
      <webElementGuid>3525b2ad-b1f1-425b-8377-4f391ae883be</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>months</value>
      <webElementGuid>9a33f3e9-2182-4235-8f88-0839f3067e3e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>6a544206-e990-4b2b-8b71-d1320bf080c5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
												Month
												January
												February
												March
												April
												May
												June
												July
												August
												September
												October
												November
												December
										</value>
      <webElementGuid>a47d1a12-ea5f-4199-80ba-d66603be9f03</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;months&quot;)</value>
      <webElementGuid>48698a41-cb19-4875-83a2-4c077bb92e15</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='months']</value>
      <webElementGuid>09faae28-cdfa-40da-98c5-5882fe742212</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='uniform-months']/select</value>
      <webElementGuid>e7e70b7b-b00f-4285-a179-acfafde53ddd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Date of Birth'])[1]/following::select[2]</value>
      <webElementGuid>d06b2ad7-8de5-4bc9-9a1f-da11f3a9f17a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[3]/following::select[2]</value>
      <webElementGuid>6a9dcb99-5e8b-40b2-8107-04c26ef333a9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sign up for our newsletter!'])[1]/preceding::select[2]</value>
      <webElementGuid>985a34bd-af6b-40ea-b584-5b8817e25da0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Receive special offers from our partners!'])[1]/preceding::select[2]</value>
      <webElementGuid>9ba62748-d668-410e-ab6f-4941b882c4a6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/select</value>
      <webElementGuid>f3deef6a-3813-43e1-b6d4-7467c817c325</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'months' and @name = 'months' and (text() = '
												Month
												January
												February
												March
												April
												May
												June
												July
												August
												September
												October
												November
												December
										' or . = '
												Month
												January
												February
												March
												April
												May
												June
												July
												August
												September
												October
												November
												December
										')]</value>
      <webElementGuid>0de4c08d-e7fd-4d5d-bd49-59c4ec3a5fd2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
