<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Register_Login_button</name>
   <tag></tag>
   <elementGuidId>fcd241b1-c5a7-4aed-b5d0-0761139931ed</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='checkoutModal']/div/div/div[2]/p[2]/a/u</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>u</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>u</value>
      <webElementGuid>9c4bba4b-448a-482a-aee0-bb09ec73e1e6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Register / Login</value>
      <webElementGuid>9b1af7e0-cb02-4fa2-90dd-d8f062133256</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;checkoutModal&quot;)/div[@class=&quot;modal-dialog modal-confirm&quot;]/div[@class=&quot;modal-content&quot;]/div[@class=&quot;modal-body&quot;]/p[@class=&quot;text-center&quot;]/a[1]/u[1]</value>
      <webElementGuid>f1ba86e1-9d09-4b7a-9753-aa5f9148fc1c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='checkoutModal']/div/div/div[2]/p[2]/a/u</value>
      <webElementGuid>e44b0ffc-6a1b-4ab6-8055-a224b4fa9b87</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Checkout'])[1]/following::u[1]</value>
      <webElementGuid>53e9baef-4941-4866-97fd-f3c092ef028a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=''])[1]/following::u[1]</value>
      <webElementGuid>061111a5-4f01-454a-810b-890a390f2df8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Continue On Cart'])[1]/preceding::u[1]</value>
      <webElementGuid>deb5a39d-3914-4010-89f4-ffc26f55ef9c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Item'])[1]/preceding::u[1]</value>
      <webElementGuid>5a261311-ead9-4932-9463-e4522e911d86</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Register / Login']/parent::*</value>
      <webElementGuid>60ca362e-c9b0-4508-9fe9-cfda884f2542</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//u</value>
      <webElementGuid>f8edb943-1daa-4eb5-b85d-57b505c99e84</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//u[(text() = 'Register / Login' or . = 'Register / Login')]</value>
      <webElementGuid>14bb5dee-4833-4602-a283-128c57394c09</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
